name: My First Workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List and Read file
              run: |
                echo "Multi-Line commands and Executing Third Party Libraries"
                ls -ltra
                cat README.md
            
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Fire and Blood, Targaryen House" >> dragon.txt




            # - name: List files
            #   run: ls

            # - name: Read file
            #   run: cat README.md