name: Multiple Jobs

on: 
 push

jobs:
    build_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: install cowsay program
        run: sudo apt install cowsay -y

      - name: execute cowsay program
        run: cowsay -f dragon "Dracarys" >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

    test_job_2:
      needs: build_job_1
      runs-on: ubuntu-latest
      steps:
        - name: Download Dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Test file exists
          run: grep -i "Dracarys" dragon.txt

    deploy_job_3:
      needs: test_job_2
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
      
      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying ... ...